Repository kleros/kleros-v2, pull requests merged in 2022-05, with the labels that each got.

#75 Feat/merkle library
  contracts/src/bridge/merkle/MerkleProof.sol
  contracts/src/bridge/merkle/MerkleTreeHistory.sol
  contracts/test/bridge/merkle/MerkleTree.ts
  contracts/test/bridge/merkle/index.ts
Labels: Type: Feature

#77 fix: sha256 leaves to avoid 2nd pre-image attack
  contracts/src/bridge/merkle/MerkleProof.sol
  contracts/src/bridge/merkle/MerkleTreeHistory.sol
  contracts/test/bridge/merkle/MerkleTree.ts
  contracts/test/bridge/merkle/index.ts
Labels: Type: Security Patch

#71 Feat: add iterations for DK jump + hidden votes setter
  contracts/src/arbitration/KlerosCore.sol
Labels: Type: Feature

#79 test: added bridge-tests for cases
  .gitignore
  contracts/deploy/01-foreign-chain.ts
  contracts/deploy/02-home-chain.ts
  contracts/src/bridge/mock/ArbSysMock.sol
  contracts/src/bridge/mock/BridgeMock.sol
  contracts/src/bridge/mock/FastBridgeSenderToEthereumMock.sol
  contracts/src/bridge/mock/InboxMock.sol
  contracts/src/bridge/mock/OutboxMock.sol
  contracts/test/pre-alpha1/index.ts
Labels: Type: Feature

#65 feat(KC): phases implementation
  contracts/deploy/00-home-chain-arbitration.ts
  contracts/src/arbitration/IDisputeKit.sol
  contracts/src/arbitration/KlerosCore.sol
  contracts/src/arbitration/dispute-kits/BaseDisputeKit.sol
  contracts/src/arbitration/dispute-kits/DisputeKitClassic.sol
  contracts/src/arbitration/dispute-kits/DisputeKitSybilResistant.sol
  contracts/test/arbitration/index.ts
  contracts/test/pre-alpha1/index.ts
Labels: Status: Review Needed, Type: Feature
