Repository kleros/kleros-v2, pull requests merged in 2022-06, with the labels that each got.

#73 Feat(web): add Home page
  package.json
  web/.yarnrc.yml
  web/codegen.yaml
  web/netlify.toml
  web/package.json
  web/src/app.tsx
  web/src/assets/svgs/icons/bookmark.svg
  web/src/assets/svgs/icons/calendar.svg
  web/src/assets/svgs/icons/chat.svg
  web/src/assets/svgs/icons/ethereum.svg
  web/src/assets/svgs/icons/french-flag.svg
  web/src/assets/svgs/icons/law-balance.svg
  web/src/assets/svgs/icons/phone.svg
  web/src/assets/svgs/icons/pile-coins.svg
  web/src/assets/svgs/icons/pnk.svg
  web/src/assets/svgs/icons/redistributed-pnk.svg
  web/src/assets/svgs/icons/snapshot-color.svg
  web/src/assets/svgs/icons/user.svg
  web/src/assets/svgs/menu-icons/dark-mode.svg
  web/src/assets/svgs/menu-icons/help.svg
  web/src/assets/svgs/menu-icons/light-mode.svg
  web/src/assets/svgs/menu-icons/notifications.svg
  web/src/assets/svgs/menu-icons/settings.svg
  web/src/assets/svgs/socialmedia/slack.svg
  web/src/components/DisputeCard/DisputeInfo.tsx
  web/src/components/DisputeCard/PeriodBanner.tsx
  web/src/components/DisputeCard/index.tsx
  web/src/components/LightButton.tsx
  web/src/components/StatDisplay.tsx
  web/src/consts/community-elements.tsx
  web/src/consts/periods.ts
  web/src/graphql/generated.ts
  web/src/hooks/queries/useHomePageQuery.ts
  web/src/hooks/useHomePageContext.tsx
  web/src/layout/footer/index.tsx
  web/src/layout/header/index.tsx
  web/src/layout/header/navbar/Menu.tsx
  web/src/layout/header/navbar/index.tsx
  web/src/pages/home.tsx
  web/src/pages/home/Community/Element.tsx
  web/src/pages/home/Community/index.tsx
  web/src/pages/home/CourtOverview/Chart.tsx
  web/src/pages/home/CourtOverview/Stats.tsx
  web/src/pages/home/CourtOverview/TimeSeriesChart.tsx
  web/src/pages/home/CourtOverview/index.tsx
  web/src/pages/home/LatestCases.tsx
  web/src/pages/home/index.tsx
  web/src/styles/global-style.ts
  web/src/styles/themes.ts
  web/tsconfig.json
  yarn.lock
Labels: Status: Review Needed, Type: Feature

#68 Feat: add subgraph
  .gitignore
  CONTRIBUTING.md
  subgraph/.eslintrc.json
  subgraph/.prettierrc
  subgraph/package.json
  subgraph/schema.graphql
  subgraph/src/FastBridgeSender.ts
  subgraph/src/HomeGateway.ts
  subgraph/src/KlerosCore.ts
  subgraph/subgraph.yaml
  subgraph/tsconfig.json
  yarn.lock
Labels: Status: Review Needed, Type: Feature

#89 feat(dk): log(n) draw
  .github/workflows/contracts-testing.yml
  contracts/src/arbitration/KlerosCore.sol
  contracts/src/arbitration/dispute-kits/DisputeKitClassic.sol
  contracts/src/arbitration/dispute-kits/DisputeKitSybilResistant.sol
  contracts/src/arbitration/mock/PNK.sol
  contracts/test/arbitration/draw.ts
Labels: Type: Enhancement :sparkles:

#94 feat(DisputeResolver): add contract
  contracts/src/arbitration/arbitrables/ArbitrableExample.sol
  contracts/src/arbitration/arbitrables/DisputeResolver.sol
Labels: Type: Feature

#93 chore: fixed the linters configuration
  .lintstagedrc.json
  .vscode/settings.json
  contracts/.eslintrc.js
  contracts/tsconfig.json
  package.json
  yarn.lock
Labels: Status: Review Needed, Type: Toolchain

#117 Chore/dependabot fixes
  .github/workflows/contracts-testing.yml
  contracts/package.json
  subgraph/package.json
  web/package.json
  yarn.lock
Labels: Type: Maintenance :construction:, Type: Security Patch

#128 chore: moved commitlint config to a separate file
  commitlint.config.js
  package.json
Labels: Type: Maintenance :construction:

#130 chore: fixed inconsistent yarn version
  .yarn/releases/yarn-3.2.0.cjs
  package.json
Labels: Type: Maintenance :construction:
