Repository kleros/kleros-v2, pull requests merged in 2022-08, with the labels that each got.

#190 feat: allow overriding a vote commitment
  contracts/src/arbitration/dispute-kits/DisputeKitClassic.sol
  contracts/src/arbitration/dispute-kits/DisputeKitSybilResistant.sol
Labels: Type: Enhancement :sparkles:

#195 Fix: Add subcourt and disputeKit creation events in KlerosCore constructor
  contracts/src/arbitration/KlerosCore.sol
  contracts/test/arbitration/index.ts
Labels: Type: Bug :bug:, Compatibility: ABI change 🗯

#200 fix: draw benchmark test is now passing
  contracts/test/arbitration/draw.ts
Labels: Type: Maintenance :construction:

#201 Fix: Modify DisputeKitCreated event
  contracts/src/arbitration/KlerosCore.sol
  contracts/test/arbitration/index.ts
Labels: Type: Enhancement :sparkles:, Compatibility: ABI change 🗯

#213 refactor: finally KlerosCore is now below 24KB
  contracts/package.json
  contracts/src/arbitration/KlerosCore.sol
  contracts/src/arbitration/dispute-kits/DisputeKitClassic.sol
  contracts/src/arbitration/dispute-kits/DisputeKitSybilResistant.sol
Labels: Type: Enhancement :sparkles:

#206 Message layout comment update
  contracts/src/bridge/FastBridgeSender.sol
Labels: Type: Documentation :books:

#231 Fix: Home page stats crashing with empty arrays in subgraph
  web/src/hooks/useHomePageContext.tsx
  web/src/pages/Home/CourtOverview/Stats.tsx
Labels: Type: Bug :bug:

#232 Feat(subgraph): Add subcourt entity and accommodate latest contract changes
  subgraph/schema.graphql
  subgraph/scripts/update.sh
  subgraph/src/FastBridgeSender.ts
  subgraph/src/KlerosCore.ts
  subgraph/subgraph.yaml
Labels: Type: Feature

#223 Feat(web): Add Dashboard page
  web/package.json
  web/src/app.tsx
  web/src/assets/svgs/styled/eth.svg
  web/src/assets/svgs/styled/pnk.svg
  web/src/components/CasesDisplay/CasesGrid.tsx
  web/src/components/CasesDisplay/Filters.tsx
  web/src/components/CasesDisplay/Search.tsx
  web/src/components/CasesDisplay/Stats.tsx
  web/src/components/CasesDisplay/StatsAndFilters.tsx
  web/src/components/CasesDisplay/index.tsx
  web/src/pages/Cases/CasesMatrix.tsx
  web/src/pages/Cases/index.tsx
  web/src/pages/Dashboard/Courts/CourtCard.tsx
  web/src/pages/Dashboard/Courts/index.tsx
  web/src/pages/Dashboard/JurorInfo/Coherency.tsx
  web/src/pages/Dashboard/JurorInfo/JurorRewards.tsx
  web/src/pages/Dashboard/JurorInfo/StakingRewards.tsx
  web/src/pages/Dashboard/JurorInfo/TokenRewards.tsx
  web/src/pages/Dashboard/JurorInfo/index.tsx
  web/src/pages/Dashboard/WithHelpTooltip.tsx
  web/src/pages/Dashboard/index.tsx
  yarn.lock
Labels: Status: Review Needed, Type: Feature
