Repository kleros/kleros-v2, pull requests merged in 2022-01, with the labels that each got.

#10 chore: github workflow for contracts testing
  .github/workflows/contracts-testing.yml
  README.md
  contracts/.gitignore
  contracts/.solcover.js
  contracts/coverage.json
Labels: Type: Toolchain

#7 Add arbitrum specific gateway contracts
  contracts/src/bridge/IL1Bridge.sol
  contracts/src/bridge/IL2Bridge.sol
  contracts/src/bridge/arbitrum/AddressAliasHelper.sol
  contracts/src/bridge/arbitrum/ArbL1Bridge.sol
  contracts/src/bridge/arbitrum/ArbL2Bridge.sol
  contracts/src/bridge/xdai/interfaces/IAMB.sol
  contracts/src/bridge/xdai/xDaiL1Bridge.sol
  contracts/src/bridge/xdai/xDaiL2Bridge.sol
  contracts/src/gateway/BaseForeignGateway.sol
  contracts/src/gateway/BaseHomeGateway.sol
  contracts/src/gateway/arbitrum/ArbitrumGateway.sol
  contracts/src/gateway/arbitrum/EthereumGateway.sol
  contracts/src/gateway/interfaces/IForeignEvidence.sol
  contracts/src/gateway/interfaces/IForeignGateway.sol
  contracts/src/gateway/interfaces/IHomeEvidence.sol
  contracts/src/gateway/interfaces/IHomeGateway.sol
  contracts/src/gateway/xdai/EthereumGateway.sol
  contracts/src/gateway/xdai/xDaiGateway.sol
Labels: Type: Feature

#24 feat(DisputeKit): change RNG for governor only
  contracts/src/arbitration/dispute-kits/DisputeKitClassic.sol
Labels: Type: Feature

#25 feat(DisputeKit): Dispute Kits abstraction for interfacing with KlerosCore
  contracts/src/arbitration/IDisputeKit.sol
  contracts/src/arbitration/KlerosCore.sol
  contracts/src/arbitration/dispute-kits/BaseDisputeKit.sol
  contracts/src/arbitration/dispute-kits/DisputeKitClassic.sol
  contracts/src/arbitration/dispute-kits/DisputeKitSybilResistant.sol
Labels: Type: Feature

#27 fix(CVE-2022-0155): upgraded follow-redirects
  contracts/package.json
  yarn.lock
Labels: Type: Security Patch

#31 chore(package-lock.json): redundant file, removed
  contracts/package-lock.json
  yarn.lock
Labels: dependencies, Type: Toolchain

#33 fix(IDisputeKit): comment
  README.md
  contracts/src/arbitration/IDisputeKit.sol
Labels: Type: Documentation :books:

#34 feat(KlerosCore): staking implementation
  contracts/src/arbitration/KlerosCore.sol
Labels: Type: Feature
